In [105]:
import pandas as pd
import numpy as np
import os

In [106]:
datapath = './data'
model_path = './save/'

## data
# AMC = pd.read_csv(os.path.join(datapath+'/'+'UTUC_deep.csv'))
ext_Hallym = pd.read_csv(os.path.join(datapath+'/'+'UTUC_deep_Hallym.csv'))
ext_SNU = pd.read_csv(os.path.join(datapath+'/'+'UTUC_deep_SNU.csv'))

train_data = pd.read_csv(os.path.join(model_path+'/'+'train_data.csv'))
test_data = pd.read_csv(os.path.join(model_path+'/'+'test_data.csv'))
valid_data = pd.read_csv(os.path.join(model_path+'/'+'valid_data.csv'))

In [107]:
AMC = pd.concat([train_data,test_data,valid_data],axis=0)

In [108]:
variables=['Age', 'Female', 'BMI', 'Pre_GFR','Location_Pelvis', 'Location_multiple', 'HUN', 'path_T', 'Path_N','Path_Grade',"Path_CIS","Prg","PFS","OS","Surv"]

In [109]:
AMC = AMC[variables]
ext_Hallym = ext_Hallym[variables]
ext_SNU  = ext_SNU[variables]

In [110]:
AMC['hospital'] = 'AMC'
ext_Hallym['hospital'] = 'Hallym'
ext_SNU['hospital'] = 'SNU'

In [111]:
AMC['Path_N'].replace({' ':np.nan},inplace=True)
AMC['Path_N'].replace({2:1},inplace=True)
AMC['Path_N'] = AMC['Path_N'].astype(float)

AMC['Location_multiple'].replace({1:0},inplace=True)
AMC['Location_multiple'].replace({2:1},inplace=True)
AMC['Location_multiple'].replace({3:1},inplace=True)
AMC['Location_multiple'].replace({4:1},inplace=True)

In [112]:
merge = pd.concat([AMC, ext_Hallym, ext_SNU], ignore_index=True)

In [113]:
from tableone import TableOne

In [114]:
AMC.columns

Index(['Age', 'Female', 'BMI', 'Pre_GFR', 'Location_Pelvis',
       'Location_multiple', 'HUN', 'path_T', 'Path_N', 'Path_Grade',
       'Path_CIS', 'Prg', 'PFS', 'OS', 'Surv', 'hospital'],
      dtype='object')

In [115]:
AMC = AMC.reset_index()

In [116]:
nonnormal= ['Age', 'BMI', 'Pre_GFR', 'PFS', 'Surv']
categorical = ['Female', 'Location_Pelvis', 'Location_multiple', 'HUN', 'path_T', 'Path_N', 'Path_Grade',
               'Path_CIS', 'Prg', 'OS','hospital']

In [117]:
Table1= TableOne(AMC, nonnormal=nonnormal, categorical=categorical, dip_test=True, normal_test=True, tukey_test=True)

In [118]:
Table1

                             Missing           Overall
n                                                  627
index, mean (SD)                   0     210.2 (158.6)
Age, median [Q1,Q3]                0  70.0 [62.0,76.0]
Female, n (%)            0         0        446 (71.1)
                         1                  181 (28.9)
BMI, median [Q1,Q3]                0  24.5 [22.6,26.4]
Pre_GFR, median [Q1,Q3]            0  75.3 [58.5,95.6]
Location_Pelvis, n (%)   0         0        310 (49.4)
                         1                  317 (50.6)
Location_multiple, n (%) 0         0        512 (81.7)
                         1                  115 (18.3)
HUN, n (%)               0         0        292 (46.6)
                         1                  335 (53.4)
path_T, n (%)            0         0           3 (0.5)
                         1                    15 (2.4)
                         2                  145 (23.1)
                         3                  155 (24.7)
                         4                   74 (11.8)
                         5                  214 (34.1)
                         6                    21 (3.3)
Path_N, n (%)            0.0     358        222 (82.5)
                         1.0                 47 (17.5)
Path_Grade, n (%)        0.0      28         96 (16.0)
                         1.0                503 (84.0)
Path_CIS, n (%)          0.0      13        363 (59.1)
                         1.0                251 (40.9)
Prg, n (%)               0.0       0        465 (74.2)
                         1.0                162 (25.8)
PFS, median [Q1,Q3]                0  36.0 [14.0,61.0]
OS, n (%)                0.0       0        443 (70.7)
                         1.0                184 (29.3)
Surv, median [Q1,Q3]               0  41.0 [23.0,64.5]
hospital, n (%)          AMC       0       627 (100.0)
[1] Hartigan's Dip Test reports possible
                                  multimodal distributions for: Age.
[2] Normality test reports non-normal
                                  distributions for: index, Age, BMI, Pre_GFR, PFS, Surv.
[3] Tukey test indicates far outliers
                                  in: Pre_GFR.

In [119]:
Table2= TableOne(merge,nonnormal=nonnormal, categorical=categorical, dip_test=True, normal_test=True, tukey_test=True)

In [120]:
Table2

                                Missing           Overall
n                                                     989
Age, median [Q1,Q3]                   0  70.0 [62.0,76.0]
Female, n (%)            0            0        694 (70.2)
                         1                     295 (29.8)
BMI, median [Q1,Q3]                   0  24.6 [22.6,26.5]
Pre_GFR, median [Q1,Q3]               2  71.6 [55.5,88.8]
Location_Pelvis, n (%)   0            0        501 (50.7)
                         1                     488 (49.3)
Location_multiple, n (%) 0            0        830 (83.9)
                         1                     159 (16.1)
HUN, n (%)               0.0          1        487 (49.3)
                         1.0                   501 (50.7)
path_T, n (%)            0.0         17          45 (4.6)
                         1.0                     20 (2.1)
                         2.0                   200 (20.6)
                         3.0                   235 (24.2)
                         4.0                   124 (12.8)
                         5.0                   323 (33.2)
                         6.0                     25 (2.6)
Path_N, n (%)            0.0        375        556 (90.6)
                         1.0                     54 (8.8)
                         2.0                      4 (0.7)
Path_Grade, n (%)        0.0         56        160 (17.1)
                         1.0                   773 (82.9)
Path_CIS, n (%)          0.0         30        635 (66.2)
                         1.0                   324 (33.8)
Prg, n (%)               0.0          1        766 (77.5)
                         1.0                   222 (22.5)
PFS, median [Q1,Q3]                   1   30.0 [9.6,57.0]
OS, n (%)                0.0          1        790 (80.0)
                         1.0                   198 (20.0)
Surv, median [Q1,Q3]                  3  34.0 [16.0,60.0]
hospital, n (%)          AMC          0        627 (63.4)
                         Hallym                107 (10.8)
                         SNU                   255 (25.8)
[1] Hartigan's Dip Test reports possible
                                  multimodal distributions for: Age.
[2] Normality test reports non-normal
                                  distributions for: Age, BMI, Pre_GFR, PFS, Surv.
[3] Tukey test indicates far outliers
                                  in: BMI, Pre_GFR.

In [121]:
Table3= TableOne(merge, groupby=['hospital'], nonnormal=nonnormal, categorical=categorical, dip_test=True, normal_test=True, tukey_test=True, pval=True, htest_name=True)

In [122]:
Table3

                                Grouped by hospital
                                            Missing           Overall               AMC             Hallym               SNU P-Value                                       Test
n                                                                 989               627                107               255
Age, median [Q1,Q3]                               0  70.0 [62.0,76.0]  70.0 [62.0,76.0]   71.0 [63.0,79.0]  71.0 [63.0,77.0]   0.127                             Kruskal-Wallis
Female, n (%)            0                        0        694 (70.2)        446 (71.1)          71 (66.4)        177 (69.4)   0.579                                Chi-squared
                         1                                 295 (29.8)        181 (28.9)          36 (33.6)         78 (30.6)
BMI, median [Q1,Q3]                               0  24.6 [22.6,26.5]  24.5 [22.6,26.4]   25.0 [22.6,27.2]  24.6 [22.8,26.4]   0.670                             Kruskal-Wallis
Pre_GFR, median [Q1,Q3]                           2  71.6 [55.5,88.8]  75.3 [58.5,95.6]   68.3 [58.0,82.5]  61.1 [49.2,78.5]  <0.001                             Kruskal-Wallis
Location_Pelvis, n (%)   0                        0        501 (50.7)        310 (49.4)          44 (41.1)        147 (57.6)   0.010                                Chi-squared
                         1                                 488 (49.3)        317 (50.6)          63 (58.9)        108 (42.4)
Location_multiple, n (%) 0                        0        830 (83.9)        512 (81.7)          96 (89.7)        222 (87.1)   0.032                                Chi-squared
                         1                                 159 (16.1)        115 (18.3)          11 (10.3)         33 (12.9)
HUN, n (%)               0.0                      1        487 (49.3)        292 (46.6)          66 (61.7)        129 (50.8)   0.013                                Chi-squared
                         1.0                               501 (50.7)        335 (53.4)          41 (38.3)        125 (49.2)
path_T, n (%)            0.0                     17          45 (4.6)           3 (0.5)          36 (33.6)           6 (2.5)  <0.001  Chi-squared (warning: expected count < 5)
                         1.0                                 20 (2.1)          15 (2.4)                              5 (2.1)
                         2.0                               200 (20.6)        145 (23.1)                            55 (23.1)
                         3.0                               235 (24.2)        155 (24.7)          22 (20.6)         58 (24.4)
                         4.0                               124 (12.8)         74 (11.8)          15 (14.0)         35 (14.7)
                         5.0                               323 (33.2)        214 (34.1)          31 (29.0)         78 (32.8)
                         6.0                                 25 (2.6)          21 (3.3)            3 (2.8)           1 (0.4)
Path_N, n (%)            0.0                    375        556 (90.6)        222 (82.5)         103 (96.3)        231 (97.1)  <0.001  Chi-squared (warning: expected count < 5)
                         1.0                                 54 (8.8)         47 (17.5)                              7 (2.9)
                         2.0                                  4 (0.7)                              4 (3.7)
Path_Grade, n (%)        0.0                     56        160 (17.1)         96 (16.0)          27 (25.2)         37 (16.3)   0.062                                Chi-squared
                         1.0                               773 (82.9)        503 (84.0)          80 (74.8)        190 (83.7)
Path_CIS, n (%)          0.0                     30        635 (66.2)        363 (59.1)         103 (96.3)        169 (71.0)  <0.001                                Chi-squared
                         1.0                               324 (33.8)        251 (40.9)            4 (3.7)         69 (29.0)
Prg, n (%)               0.0                      1        766 (77.5)        465 (74.2)          80 (74.8)        221 (87.0)  <0.001                                Chi-squared
                         1.0                               222 (22.5)        162 (25.8)          27 (25.2)         33 (13.0)
PFS, median [Q1,Q3]                               1   30.0 [9.6,57.0]  36.0 [14.0,61.0]  60.0 [25.0,102.5]   10.4 [1.8,24.1]  <0.001                             Kruskal-Wallis
OS, n (%)                0.0                      1        790 (80.0)        443 (70.7)          95 (88.8)        252 (99.2)  <0.001                                Chi-squared
                         1.0                               198 (20.0)        184 (29.3)          12 (11.2)           2 (0.8)
Surv, median [Q1,Q3]                              3  34.0 [16.0,60.0]  41.0 [23.0,64.5]  70.0 [42.0,122.5]   12.6 [1.9,25.6]  <0.001                             Kruskal-Wallis
hospital, n (%)          AMC                      0        627 (63.4)       627 (100.0)                                       <0.001                                Chi-squared
                         Hallym                            107 (10.8)                          107 (100.0)
                         SNU                               255 (25.8)                                            255 (100.0)
[1] Chi-squared tests for the following variables may be invalid due to the low number of observations: path_T, Path_N.
[2] Hartigan's Dip Test reports possible
                                  multimodal distributions for: Age.
[3] Normality test reports non-normal
                                  distributions for: Age, BMI, PFS, Pre_GFR, Surv.
[4] Tukey test indicates far outliers
                                  in: Pre_GFR.

In [123]:
Table1.to_csv(datapath+'/'+'Table1.csv')
Table2.to_csv(datapath+'/'+'Table2.csv')
Table3.to_csv(datapath+'/'+'Table3.csv')